package com.keyiflerolsun

import com.lagradost.cloudstream3.app
import com.lagradost.cloudstream3.utils.*

class VidMixi : ExtractorApi() {
    override val name = "VidMixi"
    override val mainUrl = "https://vidmixi.com"
    override val requiresReferer = true

    private val ua = "Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 " +
        "(KHTML, like Gecko) Chrome/152.0.0.0 Mobile Safari/537.36"

    private fun baseHeaders(referer: String) = mapOf(
        "User-Agent" to ua,
        "Accept" to "*/*",
        "Accept-Language" to "tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7",
        "Referer" to referer
    )

    private fun redact(url: String): String {
        if ("/m3u/" !in url) return url
        val head = url.substringBefore("/m3u/") + "/m3u/"
        val token = url.substringAfter("/m3u/")
        return head + token.take(18) + "...(${token.length})"
    }

    private fun firstHex(bytes: ByteArray, count: Int = 48): String =
        bytes.take(count).joinToString(" ") { "%02X".format(it.toInt() and 0xFF) }

    private fun tsSyncReport(bytes: ByteArray): String {
        val offsets = listOf(0, 188, 376, 564)
        return offsets.joinToString(",") { off ->
            if (off < bytes.size) "$off=${"%02X".format(bytes[off].toInt() and 0xFF)}"
            else "$off=NA"
        }
    }

    private fun absolute(base: String, value: String): String {
        if (value.startsWith("http://") || value.startsWith("https://")) return value
        return java.net.URI(base).resolve(value).toString()
    }

    private fun findM3uCandidates(html: String): List<String> {
        val decoded = html
            .replace("\\/", "/")
            .replace("\\u002F", "/")
            .replace("&amp;", "&")

        val patterns = listOf(
            Regex("""https?://[^"'\\\s<>]+/m3u/[^"'\\\s<>]+""", RegexOption.IGNORE_CASE),
            Regex("""["'](/m3u/[^"'\\\s<>]+)["']""", RegexOption.IGNORE_CASE)
        )

        return patterns.flatMap { rx ->
            rx.findAll(decoded).map { match ->
                val raw = match.groupValues.getOrNull(1)?.takeIf { it.startsWith("/") }
                    ?: match.value
                absolute(mainUrl, raw)
            }.toList()
        }.distinct()
    }

    override suspend fun getUrl(
        url: String,
        referer: String?,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ) {
        val detailReferer = referer ?: ""
        println("VIDMIXI_DIAG START embed=$url referer=$detailReferer")

        val embedHeaders = mapOf(
            "User-Agent" to ua,
            "Accept" to "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language" to "tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7"
        )

        val embed = runCatching {
            app.get(url, headers = embedHeaders, referer = detailReferer)
        }.getOrElse {
            println("VIDMIXI_DIAG FAIL stage=EMBED exception=${it::class.simpleName} message=${it.message}")
            return
        }

        val html = embed.text
        println(
            "VIDMIXI_DIAG EMBED status=${embed.code} final=${embed.url} " +
                "contentType=${embed.headers["Content-Type"]} chars=${html.length}"
        )

        listOf("provider.hlsjs.js", "jwtparser.js", "provider.cast.js", "beload.php").forEach { needle ->
            println("VIDMIXI_DIAG EMBED_MARKER name=$needle present=${html.contains(needle, ignoreCase = true)}")
        }

        val candidates = findM3uCandidates(html)
        println("VIDMIXI_DIAG M3U_CANDIDATES count=${candidates.size}")
        candidates.take(10).forEachIndexed { index, candidate ->
            println("VIDMIXI_DIAG M3U[$index]=${redact(candidate)}")
        }

        if (candidates.isEmpty()) {
            val scriptSrcs = runCatching {
                org.jsoup.Jsoup.parse(html, url)
                    .select("script[src]")
                    .map { it.absUrl("src") }
                    .filter { it.isNotBlank() }
            }.getOrDefault(emptyList())

            println("VIDMIXI_DIAG SCRIPTS count=${scriptSrcs.size}")
            scriptSrcs.take(20).forEachIndexed { index, src ->
                println("VIDMIXI_DIAG SCRIPT[$index]=$src")
            }
            println("VIDMIXI_DIAG FAIL stage=EMBED reason=M3U_NOT_PRESENT_IN_STATIC_HTML")
            println("VIDMIXI_DIAG NOTE m3u appears to be generated by browser JS/fetch; extractor stops here intentionally")
            return
        }

        for (m3uUrl in candidates) {
            val m3uHeaders = baseHeaders(url)

            val playlistResponse = runCatching {
                app.get(m3uUrl, headers = m3uHeaders, referer = url)
            }.getOrElse {
                println(
                    "VIDMIXI_DIAG M3U_FAIL url=${redact(m3uUrl)} " +
                        "exception=${it::class.simpleName} message=${it.message}"
                )
                continue
            }

            val playlist = playlistResponse.text
            val lines = playlist.lineSequence().map { it.trim() }.filter { it.isNotEmpty() }.toList()
            val segmentLines = lines.filterNot { it.startsWith("#") }
            val isHls = playlist.trimStart().startsWith("#EXTM3U")
            val isMaster = lines.any { it.startsWith("#EXT-X-STREAM-INF", ignoreCase = true) }
            val hasAudioMedia = lines.any {
                it.startsWith("#EXT-X-MEDIA", ignoreCase = true) &&
                    it.contains("TYPE=AUDIO", ignoreCase = true)
            }

            println(
                "VIDMIXI_DIAG M3U_RESULT status=${playlistResponse.code} " +
                    "contentType=${playlistResponse.headers["Content-Type"]} " +
                    "contentEncoding=${playlistResponse.headers["Content-Encoding"]} " +
                    "isHls=$isHls master=$isMaster audioMedia=$hasAudioMedia " +
                    "lines=${lines.size} mediaUrls=${segmentLines.size}"
            )

            lines.take(16).forEachIndexed { index, line ->
                val safe = if (line.startsWith("http")) redact(line) else line.take(240)
                println("VIDMIXI_DIAG PLAYLIST[$index]=$safe")
            }

            if (!isHls) {
                println("VIDMIXI_DIAG FAIL stage=M3U reason=NOT_EXTM3U")
                continue
            }

            val firstMedia = segmentLines.firstOrNull()?.let { absolute(m3uUrl, it) }
            if (firstMedia != null) {
                val mediaUri = java.net.URI(firstMedia)
                val segmentHeaders = mapOf(
                    "User-Agent" to ua,
                    "Accept" to "*/*",
                    "Accept-Language" to "tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7",
                    "Origin" to mainUrl,
                    "Referer" to "$mainUrl/"
                )

                runCatching {
                    val response = app.get(firstMedia, headers = segmentHeaders, referer = "$mainUrl/")
                    val body = response.body
                    val bytes = body.bytes()
                    body.close()

                    println(
                        "VIDMIXI_DIAG SEGMENT status=${response.code} host=${mediaUri.host} " +
                            "contentType=${response.headers["Content-Type"]} " +
                            "contentEncoding=${response.headers["Content-Encoding"]} bytes=${bytes.size}"
                    )
                    println("VIDMIXI_DIAG SEGMENT_MAGIC_HEX=${firstHex(bytes)}")
                    println("VIDMIXI_DIAG SEGMENT_TS_SYNC ${tsSyncReport(bytes)}")

                    val gzipMagic = bytes.size >= 2 &&
                        (bytes[0].toInt() and 0xFF) == 0x1F &&
                        (bytes[1].toInt() and 0xFF) == 0x8B
                    val directTs = bytes.isNotEmpty() && (bytes[0].toInt() and 0xFF) == 0x47
                    println("VIDMIXI_DIAG SEGMENT_CLASS gzipMagic=$gzipMagic directTs=$directTs")
                }.onFailure {
                    println(
                        "VIDMIXI_DIAG SEGMENT_FAIL host=${mediaUri.host} " +
                            "exception=${it::class.simpleName} message=${it.message}"
                    )
                }
            }

            val playbackHeaders = mapOf(
                "User-Agent" to ua,
                "Accept" to "*/*",
                "Origin" to mainUrl,
                "Referer" to "$mainUrl/"
            )

            println(
                "VIDMIXI_DIAG EMIT type=M3U8 url=${redact(m3uUrl)} " +
                    "referer=$mainUrl/ origin=$mainUrl"
            )

            callback(
                newExtractorLink(
                    source = name,
                    name = "$name HLS DIAG",
                    url = m3uUrl,
                    type = ExtractorLinkType.M3U8
                ) {
                    this.referer = "$mainUrl/"
                    this.quality = Qualities.Unknown.value
                    this.headers = playbackHeaders
                }
            )
            return
        }

        println("VIDMIXI_DIAG FAIL stage=FINAL reason=NO_VALID_HLS")
    }
}
